# Generated by Django 4.1.4 on 2022-12-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('is_registered', models.BooleanField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
